# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install Docker
      uses: docker/setup-buildx-action@v3
    - name: Fix Docker permissions
      run: sudo chmod 666 /var/run/docker.sock
    - name: Cache Docker images
      uses: actions/cache@v3
      with:
        path: /tmp/.testcontainers-cache
        key: ${{ runner.os }}-testcontainers-${{ hashFiles('**/*.csproj') }}
    - name: Restore dependencies
      run: dotnet restore ./src/Project.sln
      
    - name: Build
      run: dotnet build ./src/Project.sln --no-restore --configuration Debug
      
    - name: Run tests
      run: |
        dotnet test ./src/Tests/Project.Repository.Tests/Project.Repository.Tests.csproj --no-build --configuration Debug --verbosity normal
        dotnet test ./src/Tests/Project.Service.Tests/Project.Service.Tests.csproj --no-build --configuration Debug --verbosity normal
      env:
        # Для TestContainers
        TESTCONTAINERS_RYUK_DISABLED: "true"
        DOCKER_HOST: "unix:///var/run/docker.sock"
